### ISSUE TITLE
Indented blocks not working correctly

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/gjenta#17]
Command file:

```

def is_even(x):
    return x % 2 == 0

callable(is_even)

```

Invocation and output:

```
$ gjenta examples/callables.py --renderer=NATURAL
>>> 
>>> def is_even(x):
  File "<stdin>", line 2
    
    ^
IndentationError: expected an indented block
>>>     return x % 2 == 0
  File "<stdin>", line 1
    return x % 2 == 0
    ^
IndentationError: unexpected indent
>>> 
>>> callable(is_even)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'is_even' is not defined
>>> 
```

**Comment by abingham** [comment]
Try this branch: https://github.com/sixty-north/gjenta/tree/fix-indented-code-failures

There was some code in there that was adding empty, unindented lines for reason. I'm sure it made sense at some point, but it appears that it's no longer needed.
